POST https://full-stack-open-qf1l.onrender.com/api/persons
Content-Type: application/json

{ 
    "name": "Ben", 
    "number": "040-123456"
}

###

GET https://full-stack-open-qf1l.onrender.com/api/persons
    